<a href="<?php echo $this->url->getBaseUri().'event/add' ?>" class="btn btn-info"> Add </a>
<hr>
<table data-toggle="table" class="table table-dark">
    <thead class="thead-dark">
        <tr>
            <th data-field="id"> ลำดับ </th>
            <th data-field="name"> ชื่อกิจกรรม</th>
            <th data-field="date"> วันที่</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($data as $item){?>
            <tr>
                <td><?php echo $item->id ?></td>
                <td><?php echo $item->name ?></td>
                <td><?php echo $item->date ?></td>
                <td><a href="<?php echo $this->url->getBaseUri().'event/edit/'.$item->id; ?>" class="btn btn-warning">Edit</a></td>
                <td><a href="<?php echo $this->url->getBaseUri().'event/delete/'.$item->id; ?>" class="btn btn-danger navbar-btn">Delete</a></td>
            </tr>
        <?php } ?>
    </tbody>
</table>      