<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>About me </title>
</head>

<body>
  <center>
    <h1>About me </h1>
    <br/>
  <p><center><img class="img-fluid mb-7 d-block mx-auto"src="<?php echo $this->url->getBaseUri().'public/img/ya.jpg' ?>" height="100" width="150" ></center></p>
  <br>
    <h2>Name : Atitaya  Sinpakdee</h2>
    <h2>Faculty of Engineering , Chiang Mai University</h2>
    <h2>ID : 590610678</h2>
    <br>
    <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
  </center>
</body>

</html>
